# Generated by Django 5.2.7 on 2025-10-26 07:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('gform_url', models.TextField(blank=True)),
                ('google_form_id', models.CharField(blank=True, max_length=255)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending_verification', 'Pending verification'), ('suspended', 'Suspended')], default='pending_verification', max_length=32)),
                ('bio', models.TextField(blank=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=64)),
                ('education', models.JSONField(blank=True, null=True)),
                ('hear_about', models.JSONField(blank=True, null=True)),
                ('phone_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_guardian', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_first_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_last_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=64)),
                ('emergency_contact_secondary_phone', models.CharField(blank=True, max_length=64)),
                ('emergency_contact_email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_emergency_phone', models.CharField(blank=True, max_length=64)),
                ('profile_pic_uri', models.CharField(blank=True, max_length=255)),
                ('discovery_questions_answers', models.JSONField(blank=True, null=True)),
                ('opd', models.JSONField(blank=True, null=True)),
                ('opd_state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('review', 'Review'), ('final', 'Final')], max_length=16, null=True)),
                ('opd_comments', models.JSONField(blank=True, null=True)),
                ('support_needs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('capacity', models.PositiveIntegerField()),
                ('archived', models.BooleanField(default=False)),
                ('image_uri', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('enrollment_status', models.CharField(blank=True, max_length=64)),
                ('enrolled', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['archived', 'enrollment_status', 'start_date'], name='portal_prog_archive_cee9ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=64)),
                ('payment_method', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='portal.program')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_data', models.JSONField()),
                ('respondent_email', models.EmailField(blank=True, max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('not-started', 'Not started'), ('in-progress', 'In progress'), ('completed', 'Completed')], max_length=16)),
                ('submitted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='portal.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=16)),
                ('preference_order', models.IntegerField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='portal.program')),
            ],
            options={
                'indexes': [models.Index(fields=['program', 'status'], name='portal_enro_program_14be3e_idx')],
                'unique_together': {('user', 'program')},
            },
        ),
        migrations.CreateModel(
            name='BuddyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_member_assignments', to=settings.AUTH_USER_MODEL)),
                ('volunteer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_volunteer_assignments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_assignments', to='portal.program')),
            ],
            options={
                'indexes': [models.Index(fields=['program'], name='portal_budd_program_0f485c_idx'), models.Index(fields=['member_user'], name='portal_budd_member__1f5f25_idx'), models.Index(fields=['volunteer_user'], name='portal_budd_volunte_c761fa_idx')],
                'unique_together': {('program', 'member_user')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('attendance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('tardy', 'Tardy'), ('informed', 'Informed'), ('uninformed', 'Uninformed')], max_length=16)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='portal.program')),
            ],
            options={
                'unique_together': {('program', 'user', 'attendance_date')},
            },
        ),
        migrations.CreateModel(
            name='ProgramVolunteerLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_leads', to='portal.program')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['program'], name='portal_prog_program_33605a_idx'), models.Index(fields=['volunteer'], name='portal_prog_volunte_a67a14_idx')],
            },
        ),
        migrations.CreateModel(
            name='SurveyRoleAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('volunteer', 'Volunteer'), ('volunteer_lead', 'Volunteer lead'), ('teen_volunteer', 'Teen volunteer'), ('manager', 'Manager'), ('person_centered_manager', 'Person-Centered Manager'), ('admin', 'Admin')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_associations', to='portal.survey')),
            ],
            options={
                'indexes': [models.Index(fields=['survey'], name='portal_surv_survey__c97fae_idx'), models.Index(fields=['role'], name='portal_surv_role_886bc1_idx')],
                'unique_together': {('survey', 'role')},
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_links', to='portal.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_read'], name='portal_user_user_id_e42507_idx')],
                'unique_together': {('user', 'notification')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('volunteer', 'Volunteer'), ('manager', 'Manager'), ('person_centered_manager', 'Person-Centered Manager'), ('admin', 'Admin'), ('unassigned', 'Unassigned')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'role'], name='portal_user_user_id_9fd0a4_idx')],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
