# Generated by Django 5.2.7 on 2025-12-20 19:48

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('attendance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('tardy', 'Tardy'), ('informed', 'Informed'), ('uninformed', 'Uninformed')], max_length=16)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuddyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Document', max_length=255)),
                ('content', models.TextField(blank=True, help_text='HTML content from Quill editor')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('final', 'Final')], default='draft', help_text='Current state of the document', max_length=16)),
                ('published', models.BooleanField(default=False, help_text='Whether this document has a published PDF')),
                ('published_at', models.DateTimeField(blank=True, help_text='When the PDF was last generated', null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF file stored in S3/MinIO', null=True, upload_to='documents/pdfs/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Low-res thumbnail of the document generated during publish', null=True, upload_to='documents/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=16)),
                ('preference_order', models.IntegerField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentSettings',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enrollment_open', models.BooleanField(default=True, help_text='Toggle to enable or disable program enrollment/registration')),
                ('closure_reason', models.TextField(blank=True, help_text="Optional message to display when enrollment is closed (e.g., 'Registration closed for the season')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enrollment Settings',
                'verbose_name_plural': 'Enrollment Settings',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=64)),
                ('payment_method', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_images/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('enrollment_status', models.CharField(blank=True, max_length=64)),
                ('enrolled', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramVolunteerLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleEnrollmentRequirement',
            fields=[
                ('requirement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('volunteer', 'Volunteer'), ('manager', 'Manager'), ('person_centered_manager', 'Person-Centered Manager'), ('unassigned', 'Unassigned')], help_text='User role this requirement applies to', max_length=50, unique=True)),
                ('require_profile_completion', models.BooleanField(default=True, help_text='Whether profile completion is required for registration')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this requirement is currently enforced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Enrollment Requirement',
                'verbose_name_plural': 'Role Enrollment Requirements',
                'ordering': ['role'],
            },
        ),
    ]
