# Generated by Django 5.2.7 on 2025-11-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='image_uri',
        ),
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='program_images/'),
        ),
    ]
