# Generated by Django 5.2.7 on 2025-12-20 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
        ('survey', '0015_alter_answer_id_alter_category_id_alter_question_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buddyassignment',
            name='member_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_member_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buddyassignment',
            name='volunteer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_volunteer_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Manager/PCM who created this document (null if user created it themselves)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='source_survey',
            field=models.ForeignKey(blank=True, help_text='Survey used to auto-generate this document (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='survey.survey'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(help_text='The user this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollmentsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this setting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_setting_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['archived', 'enrollment_status', 'start_date'], name='portal_prog_archive_cee9ae_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='portal.program'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='portal.program'),
        ),
        migrations.AddField(
            model_name='buddyassignment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_assignments', to='portal.program'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='portal.program'),
        ),
        migrations.AddField(
            model_name='programvolunteerlead',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_leads', to='portal.program'),
        ),
        migrations.AddField(
            model_name='programvolunteerlead',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleenrollmentrequirement',
            name='required_surveys',
            field=models.ManyToManyField(blank=True, help_text='Surveys that must be completed before registration', related_name='enrollment_requirements', to='survey.survey'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', '-updated_at'], name='portal_docu_user_id_0ebe2e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_by'], name='portal_docu_created_52f0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['published'], name='portal_docu_publish_c79336_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['program', 'status'], name='portal_enro_program_14be3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'program')},
        ),
        migrations.AddIndex(
            model_name='buddyassignment',
            index=models.Index(fields=['program'], name='portal_budd_program_0f485c_idx'),
        ),
        migrations.AddIndex(
            model_name='buddyassignment',
            index=models.Index(fields=['member_user'], name='portal_budd_member__1f5f25_idx'),
        ),
        migrations.AddIndex(
            model_name='buddyassignment',
            index=models.Index(fields=['volunteer_user'], name='portal_budd_volunte_c761fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='buddyassignment',
            unique_together={('program', 'member_user')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('program', 'user', 'attendance_date')},
        ),
        migrations.AddIndex(
            model_name='programvolunteerlead',
            index=models.Index(fields=['program'], name='portal_prog_program_33605a_idx'),
        ),
        migrations.AddIndex(
            model_name='programvolunteerlead',
            index=models.Index(fields=['volunteer'], name='portal_prog_volunte_a67a14_idx'),
        ),
    ]
