# Generated by Django 5.2.7 on 2025-11-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_program_image_uri_program_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
