# Generated by Django 5.2.7 on 2025-11-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('final', 'Final')], default='draft', help_text='Current state of the document', max_length=16),
        ),
    ]
