# Generated by Django 5.2.7 on 2025-11-04 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_document_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentExport',
            fields=[
                ('export_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='PDF file of the document export', upload_to='document_exports/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this is the currently active OPD for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='portal.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='portal_docu_user_id_9c0aaf_idx'), models.Index(fields=['user', 'is_active'], name='portal_docu_user_id_ac8170_idx'), models.Index(fields=['document', '-created_at'], name='portal_docu_documen_af8b97_idx')],
            },
        ),
    ]
