# Generated by Django 5.2.7 on 2025-11-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_documentexport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
