# Generated by Django 5.2.7 on 2025-11-04 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_program_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSettings',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enrollment_open', models.BooleanField(default=True, help_text='Toggle to enable or disable program enrollment/registration')),
                ('closure_reason', models.TextField(blank=True, help_text="Optional message to display when enrollment is closed (e.g., 'Registration closed for the season')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this setting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment Settings',
                'verbose_name_plural': 'Enrollment Settings',
            },
        ),
    ]
