# Generated by Django 5.2.7 on 2025-11-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_enrollmentsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
