# Generated by Django 5.2.7 on 2025-10-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Emergency Contact Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Emergency Contact First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Emergency Contact Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=255, verbose_name='Emergency Contact Relationship'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_secondary_phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Emergency Contact Secondary Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=64, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_guardian_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Parent/Guardian Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_guardian_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Parent/Guardian Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_guardian_phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Parent/Guardian Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phone Confirmed At'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, max_length=64, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
    ]
