# Generated by Django 5.2.7 on 2025-10-29 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age_user_bio_user_emergency_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverySurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('great_things_about_you', models.TextField(blank=True, help_text='What people appreciate about you / What people like and admire about you', verbose_name='What are some great things about you?')),
                ('people_closest_to_you', models.TextField(blank=True, help_text='Who is on your team?', verbose_name='Who are the people that you are closest to?')),
                ('hobbies', models.TextField(blank=True, verbose_name='Hobbies')),
                ('activities', models.TextField(blank=True, verbose_name='Activities')),
                ('entertainment', models.TextField(blank=True, verbose_name='Entertainment')),
                ('favorite_food', models.TextField(blank=True, verbose_name='Favorite Food')),
                ('favorite_people', models.TextField(blank=True, verbose_name='Favorite People')),
                ('favorite_outings', models.TextField(blank=True, verbose_name='Favorite Outings')),
                ('routines_and_rituals', models.TextField(blank=True, verbose_name='Routines and Rituals')),
                ('good_day_description', models.TextField(blank=True, verbose_name='Describe a Good Day')),
                ('bad_day_description', models.TextField(blank=True, verbose_name='Describe a Bad Day')),
                ('perfect_day_description', models.TextField(blank=True, verbose_name='Your perfect day? What would you do from the time you wake up until you go to bed?')),
                ('hopes_and_dreams', models.TextField(blank=True, verbose_name='What are your hopes and dreams?')),
                ('important_to_you', models.TextField(blank=True, verbose_name='What do you think is important TO you?')),
                ('important_for_you', models.TextField(blank=True, verbose_name='What do you think is important FOR you?')),
                ('desired_growth_areas', models.TextField(blank=True, verbose_name='Do you have any specific desired areas of growth?')),
                ('skills_to_develop', models.TextField(blank=True, verbose_name='What skills would you like to develop?')),
                ('things_want_to_learn', models.TextField(blank=True, verbose_name='What new things would you like to learn?')),
                ('learned_at_school_liked', models.TextField(blank=True, verbose_name='What have you learned at school that you liked?')),
                ('learned_at_school_disliked', models.TextField(blank=True, verbose_name="What have you learned at school that you didn't like?")),
                ('iep_working', models.TextField(blank=True, verbose_name='What are 3 ways your IEP is working for you?')),
                ('iep_not_working', models.TextField(blank=True, verbose_name="What are 3 ways your IEP isn't working for you?")),
                ('how_communicate_needs', models.TextField(blank=True, verbose_name='How do you ordinarily communicate your needs?')),
                ('what_makes_you_happy', models.TextField(blank=True, verbose_name='What makes you happy?')),
                ('how_communicate_happy', models.TextField(blank=True, verbose_name='How do you communicate feeling happy?')),
                ('what_makes_you_sad', models.TextField(blank=True, verbose_name='What makes you sad/mad/frustrated?')),
                ('how_communicate_sad', models.TextField(blank=True, verbose_name='How do you communicate that?')),
                ('communication_style', models.JSONField(blank=True, default=dict, help_text='Stores communication preferences: words, sign language, gestures, devices, etc.')),
                ('learning_style', models.JSONField(blank=True, default=list, help_text='How do you like to learn? Visual, auditory, kinesthetic, etc.')),
                ('working_environment_preferences', models.TextField(blank=True, verbose_name='What are your environment preferences?')),
                ('virtual_learning_help', models.TextField(blank=True, verbose_name='What accommodations can we make to help you learn effectively?')),
                ('supportive_devices', models.TextField(blank=True, verbose_name='Are there any supportive devices you use to enable learning?')),
                ('ideal_staff_characteristics', models.TextField(blank=True, verbose_name='What would you like in a staff? Ideal Person?')),
                ('disliked_staff_characteristics', models.TextField(blank=True, verbose_name='What would you not like to have in a staff?')),
                ('prior_jobs', models.TextField(blank=True, verbose_name='Have you had a job? If so, what jobs have you done?')),
                ('jobs_interested_in', models.TextField(blank=True, verbose_name='What kind of jobs are you interested in?')),
                ('dream_job', models.TextField(blank=True, verbose_name='What is your dream job? What type of work do you want to do?')),
                ('employment_goals', models.TextField(blank=True, verbose_name='What are your employment goals?')),
                ('available_to_work_on', models.JSONField(blank=True, default=list, help_text='Days/times available for work')),
                ('hours_per_week_working', models.CharField(blank=True, max_length=50, verbose_name='Hours per week available')),
                ('why_interested_in_iw', models.TextField(blank=True, verbose_name='Why are you interested in Inclusive World?')),
                ('goals_and_expectations', models.TextField(blank=True, verbose_name='What are your goals and expectations?')),
                ('community_activities_interest', models.TextField(blank=True, verbose_name="Community Activities you heard about, haven't tried, but would like to learn more about?")),
                ('risk_factors', models.TextField(blank=True, help_text='Confidential information for staff', verbose_name='Any Risk Factors to be aware of')),
                ('day_program_recommendations', models.TextField(blank=True, help_text='Summarize areas they would like support in', verbose_name='Day Program Recommendations')),
                ('has_ged_or_diploma', models.BooleanField(blank=True, null=True, verbose_name='Do you have a GED or High School Diploma?')),
                ('training_courses_completed', models.TextField(blank=True, verbose_name='List any training courses completed or certified in')),
                ('how_heard_about_us', models.JSONField(blank=True, default=list, help_text='Sources: Family/Friends, Social Media, etc.')),
                ('form_helper', models.CharField(blank=True, max_length=255, verbose_name='Who helped you work on this form today?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_survey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discovery Survey',
                'verbose_name_plural': 'Discovery Surveys',
            },
        ),
    ]
