# Generated by Django 5.2.7 on 2025-10-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_discoverysurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoverysurvey',
            name='available_to_work_on',
            field=models.JSONField(blank=True, default=None, help_text='Days/times available for work', null=True),
        ),
        migrations.AlterField(
            model_name='discoverysurvey',
            name='communication_style',
            field=models.JSONField(blank=True, default=None, help_text='Stores communication preferences: words, sign language, gestures, devices, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='discoverysurvey',
            name='how_heard_about_us',
            field=models.JSONField(blank=True, default=None, help_text='Sources: Family/Friends, Social Media, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='discoverysurvey',
            name='learning_style',
            field=models.JSONField(blank=True, default=None, help_text='How do you like to learn? Visual, auditory, kinesthetic, etc.', null=True),
        ),
    ]
