# Generated by Django 5.2.7 on 2025-10-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_discoverysurvey_available_to_work_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('volunteer', 'Volunteer'), ('person_centered_manager', 'Person Centered Manager'), ('manager', 'Manager'), ('admin', 'Admin')], default='member', help_text="User's role in the organization", max_length=50, verbose_name='Role'),
        ),
    ]
