# Generated by Django 5.2.7 on 2025-11-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_role_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='support_needs',
            field=models.TextField(blank=True, help_text='Special accommodations or support requirements', verbose_name='Support Needs'),
        ),
    ]
