# Generated by Django 5.2.7 on 2025-11-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('volunteer', 'Volunteer'), ('person_centered_manager', 'Person Centered Manager'), ('manager', 'Manager')], default='member', help_text="User's role in the organization", max_length=50, verbose_name='Role'),
        ),
    ]
