# Generated by Django 5.2.7 on 2025-11-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='available_to_work_on',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='bad_day_description',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='communication_style',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='community_activities_interest',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='day_program_recommendations',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='desired_growth_areas',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='disliked_staff_characteristics',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='dream_job',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='employment_goals',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='entertainment',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='favorite_food',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='favorite_outings',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='favorite_people',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='goals_and_expectations',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='good_day_description',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='has_ged_or_diploma',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='hopes_and_dreams',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='hours_per_week_working',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='how_communicate_needs',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='how_heard_about_us',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='ideal_staff_characteristics',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='important_for_you',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='important_to_you',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='jobs_interested_in',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='perfect_day_description',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='risk_factors',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='routines_and_rituals',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='skills_to_develop',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='training_courses_completed',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='virtual_learning_help',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='why_interested_in_iw',
        ),
        migrations.AddField(
            model_name='discoverysurvey',
            name='things_like_to_do',
            field=models.TextField(blank=True, verbose_name='What kinds of things do you like to do at home, outside, and just for fun? Who do you like doing them with? Why?'),
        ),
        migrations.AddField(
            model_name='discoverysurvey',
            name='who_to_turn_to',
            field=models.TextField(blank=True, verbose_name='Who do you turn to when you need help?'),
        ),
        migrations.AlterField(
            model_name='discoverysurvey',
            name='great_things_about_you',
            field=models.TextField(blank=True, verbose_name="What are some great things about you that you'd like us to know about? What great things do people say about you?"),
        ),
        migrations.AlterField(
            model_name='discoverysurvey',
            name='iep_not_working',
            field=models.TextField(blank=True, verbose_name="What are 3 ways your Individualized Education Program (IEP) isn't working for you? How can Inclusive World support you there?"),
        ),
        migrations.AlterField(
            model_name='discoverysurvey',
            name='iep_working',
            field=models.TextField(blank=True, verbose_name='What are 3 ways your Individualized Education Program (IEP) is working for you?'),
        ),
        migrations.AlterField(
            model_name='discoverysurvey',
            name='learned_at_school_disliked',
            field=models.TextField(blank=True, verbose_name="What have you learned at school that you didn't like? Why didn't you like it? Could it have been presented differently?"),
        ),
        migrations.AlterField(
            model_name='discoverysurvey',
            name='learned_at_school_liked',
            field=models.TextField(blank=True, verbose_name='What have you learned at school that you liked? Why did you like it?'),
        ),
        migrations.AlterField(
            model_name='discoverysurvey',
            name='learning_style',
            field=models.JSONField(blank=True, default=None, help_text='How do you like to learn? Check all that apply.', null=True),
        ),
        migrations.AlterField(
            model_name='discoverysurvey',
            name='people_closest_to_you',
            field=models.TextField(blank=True, help_text='At home, at school, friends', verbose_name='Who is on your team?'),
        ),
        migrations.AlterField(
            model_name='discoverysurvey',
            name='things_want_to_learn',
            field=models.TextField(blank=True, verbose_name='What new things would you like to learn to do at home, outside, and just for fun? With whom would you like to learn to do them? Why?'),
        ),
        migrations.AlterField(
            model_name='discoverysurvey',
            name='working_environment_preferences',
            field=models.TextField(blank=True, verbose_name='What are your environment preferences? Please share your environmental sensitivity.'),
        ),
    ]
