# Generated by Django 5.2.7 on 2025-11-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_discoverysurvey_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='how_communicate_happy',
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='how_communicate_sad',
        ),
        migrations.AlterField(
            model_name='discoverysurvey',
            name='what_makes_you_happy',
            field=models.TextField(blank=True, verbose_name='What makes you happy? How do you communicate feeling happy?'),
        ),
        migrations.AlterField(
            model_name='discoverysurvey',
            name='what_makes_you_sad',
            field=models.TextField(blank=True, verbose_name='What makes you sad/mad/frustrated? How do you communicate that?'),
        ),
    ]
