# Generated by Django 5.2.7 on 2025-11-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_discoverysurvey_how_communicate_happy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='who_to_turn_to',
        ),
        migrations.AlterField(
            model_name='discoverysurvey',
            name='people_closest_to_you',
            field=models.TextField(blank=True, help_text='At home, at school, friends', verbose_name='Who is on your team? Who do you turn to when you need help?'),
        ),
    ]
