# Generated by Django 5.2.7 on 2025-11-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_discoverysurvey_who_to_turn_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discoverysurvey',
            options={'verbose_name': 'Discovery Questions', 'verbose_name_plural': 'Discovery Questions'},
        ),
        migrations.RemoveField(
            model_name='discoverysurvey',
            name='learned_at_school_disliked',
        ),
    ]
