# Generated by Django 5.2.7 on 2025-11-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_discoverysurvey_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverysurvey',
            name='learned_at_school_disliked',
            field=models.TextField(blank=True, verbose_name="What have you learned at school that you didn't like? Why didn't you like it? Could it have been presented differently?"),
        ),
    ]
