#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Function to wait for PostgreSQL to be ready
postgres_ready() {
python << END
import sys
import psycopg

try:
    psycopg.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="postgres",
        port="5432",
    )
except psycopg.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}

# Wait for PostgreSQL
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

# Note: Migrations are handled by Makefile during 'make up'
# This allows for fresh migration generation on each startup

exec "$@"
